### ISSUE TITLE
Newly opened terminal has two tabs, one is unresponsive

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-term#146] opened 2024-02-27 02:28 UTC
Newly opened terminal has two tabs, the first one is unresponsive until clicked. What it looks like is that the process of that tab is not drawing unless it receives a mouse-button input.

**Comment by leviport** [comment] 2024-02-27 14:28
I believe this is a duplicate of https://github.com/pop-os/cosmic-term/issues/36 (and probably related to https://github.com/pop-os/cosmic-term/issues/50). I'll close this and reopen #36

**Closed by leviport** 2024-02-27 14:28 UTC
