### ISSUE TITLE
Nerd font doesn't work.

### ISSUE THREAD

**Issue by drazil100** [pop-os/cosmic-term#279] opened 2024-08-09 02:49 UTC
I am using DejaVuSandMono Nerd Font Mono and btop is failing to render the graph portions correctly. 
![screenshot-2024-08-09-02-43-58](https://github.com/user-attachments/assets/76dffdc5-5a66-4fcb-a518-e36fbe6aa280)

For reference this is what it should look like. 
![Dusklight-bpytop](https://github.com/user-attachments/assets/524ea66c-99c5-4df3-8e98-3a6860960ea1)

**Comment by RossBarnie** [comment] 2024-08-09 13:29
Duplicate of #275

**Closed** 2024-08-12 10:26 UTC
