### ISSUE TITLE
White vertical lines are visible inside Neovim

### ISSUE THREAD

**Issue by s1n7ax** [pop-os/cosmic-term#58] opened 2024-01-17 05:28 UTC
Following is an screenshot of Alacritty (LHS) and Cosmic-term (RHS). When It's opened, they look normal. However, When Neovim is opened, I can see white line between characters.

**Steps to reproduce:**
1. Install neovim in Alacritty & Cosmic-term
2. Set the `JetBrainsMonoNL` font in both terminals
3. Launch `nvim --clean -c ":highlight Normal ctermbg=blue"`

![image](https://github.com/pop-os/cosmic-term/assets/18459807/85dd6f89-0930-4c81-89ca-e5ed87074a73)

![image](https://github.com/pop-os/cosmic-term/assets/18459807/2076643d-3d85-461a-bc5f-bc90a3bb9545)

![image](https://github.com/pop-os/cosmic-term/assets/18459807/e383faa4-0f0e-49b3-b9d9-563eb74fbf67)

**Comment by s1n7ax** [comment] 2024-01-17 05:29
Actually, looks like selecting the text shows similar behavior where the background color leaking through the space between characters.

![image](https://github.com/pop-os/cosmic-term/assets/18459807/b924d506-3ebf-43c2-926f-957ac67071d8)

**Comment by SecretVal** [comment] 2024-01-17 14:32
Yeah, I have the same problem.

**Comment by jackpot51** [comment] 2024-01-17 15:12
What version of cosmic-term?

**Comment by s1n7ax** [comment] 2024-01-17 17:07
@jackpot51 No idea how to get that information from the binary but nixpkgs derivation uses following commit hash right now `bf3f507fdd73a06ab1f9b199a98dca6988aafec2`
https://github.com/NixOS/nixpkgs/blob/c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370/pkgs/by-name/co/cosmic-term/package.nix#L29

**Comment by MoSal** [comment] 2024-01-17 17:15
I have a hunch that this and #43 could be helped by pop-os/cosmic-text#212

**Comment by MoSal** [comment] 2024-01-17 19:25
> I have a hunch that this and #43 could be helped by [pop-os/cosmic-text#212](https://github.com/pop-os/cosmic-text/pull/212)

Or maybe not. Unlike #43, I can't reproduce this.

**Comment by jackpot51** [comment] 2024-01-17 20:17
It is probable that updating the nix package would help. It is from before tons of fixes, including combining matching background rects.

**Comment by jackpot51** [comment] 2024-01-17 20:19
I'm pretty sure this is fixed in `master` and indicates an issue with packaging not being up to date, which is out of the scope of this repository.

**Closed by jackpot51** 2024-01-17 20:19 UTC
