### ISSUE TITLE
Misalignment with panes in TUI

### ISSUE THREAD

**Issue by tracer123** [pop-os/cosmic-term#367] opened 2024-11-01 22:15 UTC
Left is kitty, right is cosmic-term. There is an obvious misalignment of some kind and it just gets worse the longer you have it up.

![screenshot-2024-11-01-22-04-26](https://github.com/user-attachments/assets/a2fb20a5-9623-4503-b0d7-324c2d1f9a77)

**Comment by leviport** [comment] 2024-11-01 22:17
Duplicate of https://github.com/pop-os/cosmic-text/issues/237

**Closed by leviport** 2024-11-01 22:17 UTC
