### ISSUE TITLE
Terminal is not focused when launched

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/cosmic-term#107] opened 2024-02-01 19:13 UTC
When the terminal starts, I have to click it to be able to type stuff. A tab should always be focused so that typing always works (unless you have a menu open I guess).

**Comment by jacobgkau** [comment] 2024-02-02 23:29
Adding to this, clicking the titlebar of the window makes the terminal itself lose focus. (That creates a problem for the common use case of dragging the terminal around by the titlebar, then trying to use it.)

**Comment by git-f0x** [comment] 2024-02-04 20:29
Also, pasting something inside using the context menu makes the terminal lose focus.
Though I'm not experiencing the terminal being unfocused when launched.

**Comment by snaggen** [comment] 2024-02-05 11:55
I cannot reproduce the terminal not being focused after start. This might possibly be fixed by https://github.com/pop-os/cosmic-term/commit/4401a7dbef3e1579af9694c5f6c38c1b788a86e2 
So, please retest with latest master and see if the focus on start is still there?

**Comment by WatchMkr** [comment] 2024-05-25 15:43
Original issue appears fixed. Clicking the header and losing focus is tracked on libcosmic here: https://github.com/pop-os/libcosmic/issues/431

**Closed by WatchMkr** 2024-05-25 15:43 UTC
